/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package registro;
import java.sql.Connection;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;
import main.*;
import metodos.*;

/**
 *
 * @author eduar
 */
public class Registro extends javax.swing.JFrame {

    /**
     * Creates new form Registro
     */
    public Registro() {
        initComponents();
        this.setLocationRelativeTo(null);
        lblini.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    conexion cc=new conexion();
     Connection con=cc.getConnection();
     
     public void AgregarUsuario(){
       String pass=String.valueOf(PasswordFieldUsuario.getPassword());
       String rol=String.valueOf(txtUsuarioLogin1.getText());
       String SQL="insert into usuarios(Usuarios,Contraseña,roles) value(?,?,?)";
      
       try{
           PreparedStatement pst=con.prepareStatement(SQL);
       pst.setString(3, txtTipoUser.getText());
       pst.setString(2, pass);
       pst.setString(1, rol);
       
       pst.executeUpdate();
       JOptionPane.showMessageDialog(null, "Registro exitoso");
       }catch (Exception e){
           JOptionPane.showMessageDialog(null,"Error de registro"+e.getMessage());
       }
   }
     
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblhouse = new javax.swing.JLabel();
        lblini = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtTipoUser = new javax.swing.JTextField();
        PasswordFieldUsuario = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtUsuarioLogin1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblhouse.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblhouse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/casa.png"))); // NOI18N
        lblhouse.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblhouse.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lblhouseMouseMoved(evt);
            }
        });
        lblhouse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblhouseMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblhouseMouseExited(evt);
            }
        });
        jPanel1.add(lblhouse, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 240, 70, 80));

        lblini.setFont(new java.awt.Font("Agency FB", 0, 18)); // NOI18N
        lblini.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblini.setText("INICIO");
        jPanel1.add(lblini, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 320, 50, -1));

        jLabel1.setFont(new java.awt.Font("Agency FB", 0, 18)); // NOI18N
        jLabel1.setText("REGISTRO");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, 50, -1));

        jLabel2.setText("Usuario");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, -1));

        txtTipoUser.setFont(new java.awt.Font("Arial Narrow", 0, 14)); // NOI18N
        txtTipoUser.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtTipoUser.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(txtTipoUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, 170, -1));

        PasswordFieldUsuario.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        PasswordFieldUsuario.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(PasswordFieldUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 140, 170, -1));

        jLabel3.setText("Password");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, -1, -1));

        jLabel4.setText("Tipo usuario (admin/visita)");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        jLabel5.setFont(new java.awt.Font("Agency FB", 0, 18)); // NOI18N
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/mas.png"))); // NOI18N
        jLabel5.setText("AGREGAR");
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, -1, -1));

        txtUsuarioLogin1.setFont(new java.awt.Font("Arial Narrow", 0, 14)); // NOI18N
        txtUsuarioLogin1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtUsuarioLogin1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(txtUsuarioLogin1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, 170, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 380, 350));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblhouseMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblhouseMouseMoved
       lblini.setVisible(true);
    }//GEN-LAST:event_lblhouseMouseMoved

    private void lblhouseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblhouseMouseExited
        lblini.setVisible(false);
    }//GEN-LAST:event_lblhouseMouseExited

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
   
        String pas = PasswordFieldUsuario.getText();
        String usuario = txtUsuarioLogin1.getText();
        int band=0;
        if (pas==usuario) {
            band=1;
        }
        
        if( (txtTipoUser.getText().equals("admin") || txtTipoUser.getText().equals("visita")) )
        {
        AgregarUsuario();
        }
        
        else{
            JOptionPane.showMessageDialog(null,"¡Ingresa bien el tipo de usuario'");
        }
            
        
    }//GEN-LAST:event_jLabel5MouseClicked

    private void lblhouseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblhouseMouseClicked
        this.dispose();
    }//GEN-LAST:event_lblhouseMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField PasswordFieldUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblhouse;
    private javax.swing.JLabel lblini;
    private javax.swing.JTextField txtTipoUser;
    private javax.swing.JTextField txtUsuarioLogin1;
    // End of variables declaration//GEN-END:variables
}
